### ISSUE TITLE
Controlling motor loads

### ISSUE THREAD

**Issue by ReTo007** [Feller-AG/wiser-tutorial#12]
@woodworm:

Hi there, 

I'm interfacing to my Feller Wiser system and trying to upgrade the existing Home Assistant integration. I stumbled across a couple of question regarding motor loads:
- The Feller iOS app and eSetup app provide the option to change the motor step size: 100ms, 200ms, 300ms, etc. Is this info as well exposed via the API? I'm unable to find.
- The Feller iOS eSetup app provides the option to change the type of blind, i.e. "Lamellenstore", "Rollladen", "Markise". Is this info as well exposed via the API? Again, I'm unfortunately unable to find it.

Thanks for your help.

Cheers, ReTo

**Comment by ReTo007** [comment]
So, I found the answer to my first question here: 
GET /api/devices/config/{config_id}

**Comment by woodworm** [comment]
It is easier if you manage this information ("Lamellenstore", "Rollladen", "Markise") with your own property in the load object.
for example:
`PATCH api/loads/<id> {"home_assistant_type": "rollladen"}`
The data modeling of the eSetup-APP is not publicly documented and can also change.
So you never have compatible problems.

**Comment by ReTo007** [comment]
Understood, all clear. Thanks for your feedback!
