### ISSUE TITLE
Control usage

### ISSUE THREAD

**Issue by JJSarrasin** [Feller-AG/wiser-tutorial#3]
Hi guys,

Thanks for the start of the API.

Can you elaborate more on a scenario for the control usage (PUT /api/loads/< id >/ctrl). In what case would we want to use this API instead of the target state ? It implies to do an action followed by a timer and another action.

I plan to use fully wiser in my new home in the following week and do all the client app myself, but 1 hardware limitation is pending on this decision: Dim for DALI..

I also wait on more API documentation

Thanks,

JJ

**Comment by woodworm** [comment]
PUT /api/loads/< id >/ctrl is designed for user interfaces like this:
The load behaves the same way as you would control it with a button on the wall.
```
+-----+
| I/0 |
+-----+
```
```
+-----+  +-----+      +-----+  +-----+       +-----+  +-----+  
|  +  |  |  -  |      |  ^  |  |  v  |       |  I  |  |  0  |
+-----+  +-----+      +-----+  +-----+       +-----+  +-----+
```
PUT /api/loads/< id >/target_state is designed for user interfaces like this:
For sliders or color pickers
```
           +-+
+----------| |-------------------+
|          | |                   |
+----------| |-------------------+
           +-+
```

DALI and more API documentation is currently under construction.
