### ISSUE TITLE
ID not found

### ISSUE THREAD

**Issue by Webbeh** [Feller-AG/wiser-tutorial#8]
Hi.

Trying to develop a Node-Red adapter for Wiser, I encounter issues from the get-go.

I can get the API token easily enough, but run into issues when I try to interact with a load.

I only got one device (3401.A - one load on/off button with wifi) that's connected. No other device.
C firmware version : 0x50005000
A firmware version : 0x10100712
mPi : 1.14.0-142 (commit 569acf3)

I can get the list of loads through `/api/loads` :
![image](https://user-images.githubusercontent.com/1530837/161371914-28b694c5-f95e-46d4-abd7-9d3c4fa0d38d.png)

However, as soon as I try to interact with that load in any way, it just gives me an "ID not found" error. This happens in all of those endpoints : 
- `/api/loads/1/ctrl`
- `/api/loads/1/target_state`
- `/api/loads/1/state`

If I try to query `/api/loads/state`, it returns me an empty array...
![image](https://user-images.githubusercontent.com/1530837/161371970-f6b7a344-3725-4537-b465-2cc5fa4ef887.png)

...Is there anything I'm doing wrong ?

Thank you...

**Comment by flumflum** [comment]
Hi @Webbeh 

thank you for posting your issue.

Can you try the following URLs, just using a browser (not over the Node-Red-Adapter)
I assume that your Wiser-Gateway has IP-Address `172.22.22.59`

1)  `http://172.22.22.59/api/loads`
2)  `http://172.22.22.59/api/loads/1`
3)  `http://172.22.22.59/api/loads/state`
4)  `http://172.22.22.59/api/loads/1/state`

Thank you...

**Comment by Webbeh** [comment]
![image](https://user-images.githubusercontent.com/1530837/161815045-3a4f21a2-8c69-4816-8258-b4acca2a7b60.png)

Same result with Reqbin, Postman and, obviously, Node-Red.

**Comment by flumflum** [comment]
Okay, 

thanks for reply.

Can you send me your device information:
`http://172.22.22.59/api/devices/00009de5`

**Comment by Webbeh** [comment]
```json
{
  "data": {
    "inputs": [
      {
        "type": "toggle"
      }
    ],
    "outputs": [
      {
        "type": "onoff"
      }
    ],
    "a": {
      "hw_id": "0x1110",
      "nubes_id": 68954,
      "fw_version": "0x10100712",
      "address": "0x00009de5",
      "comm_name": "Druckschalter 1K",
      "serial_nr": "011110_B_007021",
      "fw_id": "0x0100",
      "comm_ref": "3401.A"
    },
    "last_seen": 109,
    "id": "00009de5",
    "c": {
      "hw_id": "0x8613",
      "nubes_id": 57177,
      "fw_version": "0x50005000",
      "cmd_matrix": "0x0101",
      "comm_name": "Druckschalter 1K WLAN",
      "serial_nr": "018613_B_000860",
      "fw_id": "0x8692",
      "comm_ref": "926-3401.1.W.A"
    }
  },
  "status": "success"
}
```

**Comment by Webbeh** [comment]
Here's the result of the extended device diagnostic, as well.


```


************************************

Start Extended System-Diagnostics 🛫

************************************

 

Read System Information 🔎..

1 Devices to check.

 

Read Device RSSI 🔎..

 

RSSI of total 1 devices (0 RSSI values)

Signal Min: 150000 Max: 0 Mean: NaN

Noise Min: 5000 Max: 0 Mean: NaN

Signal/Noise ratio (SNR) Min: 100000 Max: 0 Mean: NaN

- Signal OK (Min > 1000) 👍

- Noise OK (Max < 7500) 👍

- SNR OK  (Min > 20) 👍

 

RSSI diagram: 

Signal  0|¦|0

Noise   0|¦· · · · · · · · · · · · · · · · · · · · ¦· · · · · · · · · · ·|7500

 

Read Device NOISE 🔎..

Device 00009de5: {"floor":41,"floor_peak":43,"floor_mean":33,"floor_base":12}

 

Noise of total 1 devices

Noise floor Min: 41 Max: 41 Mean: 41

- Noise floor OK (Max < 7500) 👍

 

Noise diagram: 

peak    0|·¦O¦ · · · · · · · · · · · · · · · · · · · · · · · · · · · · · ·|7500

floor   0|·¦O¦ · · · · · · · · · · · · · · · · · · · · · · · · · · · · · ·|7500

mean    0|·¦O¦ · · · · · · · · · · · · · · · · · · · · · · · · · · · · · ·|7500

base    0|·¦O¦ · · · · · · · · · · · · · · · · · · · · · · · · · · · · · ·|7500

 

Read Device Health Check Information 🔎..

Device 00009de5: {"kplus":0,"current_ch0":0,"flash":0,"current_ch1":0,"zero_cross":0,"mag":0,"dc_voltage":0,"temp_ch1":0,"temp_ch0":0}

All 1 devices are healthy! 👍

 

Check Short Frame Data Transmission over K+ 🔎

Start Transmission... .................................

Read Error Registers 🔎..

Device 00009de5: {"rx_errors":0}..

Device 00009de5: {"noise_warn_cnt":0}

Transmission successful (without errors)! 👍

 

Check Long Frame Data Transmission over K+ 🔎

Start Transmission... .......................

Read Error Registers 🔎..

Device 00009de5: {"rx_errors":0}..

Device 00009de5: {"noise_warn_cnt":0}

Transmission successful (without errors)! 👍

 

 

Generate Tx-Burst and read Test-Result (This may take 2 seconds) 🔎....

Device 00009de5: 655350

Burst Signal of 1 devices

Signal max:655350; min:150000; mean:655350

 - OK (min > 205) 👍

 

Burst signal diagram: 

Burst signal    0|· · · · · · · ¦----------------------------------------------O¦|655350

 

*****************************************

 Extended System-Diagnostics Completed 🏁

          All tests PASSED 👍

*****************************************

 

**************************************

Start Device Health Condition Check 🛫

**************************************

 

Read System Information 🔎..

1 Devices to check.

 

* A-Block checks *

 

Read Device Health Check Information 🔎..

Device 00009de5: {"kplus":0,"current_ch0":0,"flash":0,"current_ch1":0,"zero_cross":0,"mag":0,"dc_voltage":0,"temp_ch1":0,"temp_ch0":0}

All 1 devices are healthy! 👍

 

Read Device DC Voltage 🔎..

Device 00009de5: 23.9 VDC

Voltages of 1 devices

 

Read RSSF Free Blocks 🔎..

Device 00009de5: Free blocks: 1475

RSSF Free Blocks of 1 devices

 

Read RSSF Erased Pages Counter 🔎..

Counters of 0 devices

 

Read Switch ON counter Channel 1 🔎..

Device 00009de5: Switch ON count: 31

Counters of 1 devices

 

Read Switch ON counter Channel 2 🔎..

Device 00009de5: Switch ON count: NaN

Counters of 1 devices

 

Read Peak Temperature CH 1 🔎..

Temperatures of 0 devices

 

Read Peak Temperature CH 2 🔎..

Temperatures of 0 devices

 

* C-Block checks *

 

Read Device Health Check Information 🔎..

Device 00009de5: {"health_check_errors":0}

All 1 devices are healthy! 👍

 

Read Device DC Voltage 🔎..

Device 00009de5: 24.2 VDC

Voltages of 1 devices

 

 

*******************************************

 Device Health Condition Check Completed 🏁

          All tests PASSED 👍

*******************************************


```

**Comment by Webbeh** [comment]
Also, I tried integrating it now in the Wiser eSetup app, and I got an error : 
`Error : Load 1 not found`

on the app, after pairing the device (press of the button when the app asks for it).

**Comment by Webbeh** [comment]
Last but not least, I tried : 
- Checking whether a new version of the firmware was available on the cloud - which returned negative
- Re-applying the current firmware to the device (the bottom right led flashed pale red during the flash)

This had no effect, the problem persists.

**Comment by flumflum** [comment]
# Wiser-by-Feller WLAN-gateway reset-functions

By pressing the reset-button **(1)** for a while its possible to reboot or even to reset the WLAN gateway.

![wiser-by-feller-wlan-gateway-reset-button-overview](https://user-images.githubusercontent.com/62331526/162911506-52f531b6-a98b-4664-838c-68ce2f79a87c.png)


Press the reset-button **(1)** until the LED **(2)** color change to your desired function and then release the button.

Possible functions according LED color:
![wiser-by-feller-wlan-gateway-reset-button-short-description](https://user-images.githubusercontent.com/62331526/162911564-85f9cf38-4cff-42e2-9ec1-8902a21b0e55.png)



🟢 reboot the WLAN-gateway
- No data will be erased

🔵 network-config reset
- WLAN configurations will be removed
- WLAN-gateway is set in Access-Point-Mode

🔴 factory-reset
- Set WLAN-gateway to factory-settings
- All configured settings (WLAN, ...) will be deleted
- WLAN-gateway is set in Access-Point-Mode

**Comment by Webbeh** [comment]
So, apparently, a factory reset seemed to do the trick.

Note, however, that for whatever reason, the backlight settings stayed saved on this device (I set them to red for off and green for on, and it stayed so after factory reset and even after a power cycle).

Thank you !
